version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_blindbeat
    command: --replSet rs0
    restart: always
    networks:
      - mongo
    volumes:
      - dbdata:/data/db
      - ./init-replica-set.js:/docker-entrypoint-initdb.d/init-replica-set.js

  discord-bot:
    build: .
    container_name: blindbeat
    restart: always
    networks:
      - mongo
    depends_on:
      - mongodb
    env_file: .env

volumes:
  dbdata: {}

networks:
  mongo:
    driver: bridge
